### ISSUE TITLE
TypeError: 'instancemethod' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by wangguoweimmg** [Rui-L/RCN_CNN_SVM_KNN-EMNIST#1]
Please could someone tell me what's wrong with it and explain why. Thanks.Below is the full traceback.

Traceback (most recent call last):
  File "rcn.py", line 145, in <module>
    num_per_class_testing=args.num_per_class_testing)
  File "rcn.py", line 82, in run
    train_results = pool.map_async(train_partial, [d[0] for d in train_data]).get(9999999)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
TypeError: 'instancemethod' object has no attribute '__getitem__'

**Comment by Rui-L** [comment]
Looks like this error comes from `multiprocessing.Pool`. I suggest you run some isolated tests for the `Pool.map_async` function. See this [link](https://docs.python.org/2/library/multiprocessing.html) for docs about `Pool`.

Besides, I am using `science_rcn` commit version 405d25.
